// Render a ResultsDoc to a deterministic RESULTS.md table. Regenerated, never
// hand-edited (spec AC-10.12). Every row is keyed by engine + workload id so perf
// claims map 1:1 to a workload (AC-10.13).

import type { Cell, EngineInfo, ResultsDoc, RunContext } from "./results.ts";
import type { Summary } from "./stats.ts";

function ms(s: Summary | null): string {
  if (!s || Number.isNaN(s.p50)) return "—";
  return `${s.p50.toFixed(2)}/${s.p95.toFixed(2)}`;
}

function kb(bytes: number | null): string {
  return bytes === null ? "—" : `${(bytes / 1024).toFixed(1)}`;
}

function sim(x: number | null): string {
  return x === null ? "—" : x.toFixed(3);
}

function num(x: number | null, digits: number): string {
  return x === null ? "—" : x.toFixed(digits);
}

function cellRow(c: Cell): string {
  const tail = c.error ? ` | ${c.error}` : "";
  return (
    `| ${c.engine} | ${c.workload} | ${ms(c.warm)} | ${ms(c.cold)} | ` +
    `${ms(c.initMs)} | ${num(c.throughputPerSec, 1)} | ${kb(c.peakRssBytes)} | ` +
    `${kb(c.pdfBytes)} | ${sim(c.similarity)}${tail} |`
  );
}

function contextBlock(ctx: RunContext): string {
  return [
    "## Machine & run context",
    "",
    `- Date (pinned): ${ctx.date}`,
    `- OS: ${ctx.os} (${ctx.arch})`,
    `- CPU: ${ctx.cpuModel} — ${ctx.cores} logical cores`,
    `- Memory: ${(ctx.totalMemBytes / 1024 ** 3).toFixed(1)} GiB`,
    `- Node: ${ctx.nodeVersion}`,
    `- Runs/warmup: ${ctx.runs} measured, ${ctx.warmup} warmup`,
    `- PNG equivalence reference engine: ${ctx.referenceEngine}`,
    "",
  ].join("\n");
}

function enginesBlock(engines: readonly EngineInfo[]): string {
  const head = "| Engine | Kind | Available | Version | Ships browser | Footprint notes |";
  const sep = "|---|---|---|---|---|---|";
  const rows = engines.map((e) => {
    const a = e.availability;
    const status = a.available ? "yes" : `no (${a.reason ?? "?"})`;
    return `| ${e.id} | ${e.kind} | ${status} | ${a.version ?? "—"} | ${e.footprint.shipsBrowser ? "yes" : "no"} | ${e.footprint.notes} |`;
  });
  return ["## Engines", "", head, sep, ...rows, ""].join("\n");
}

function metricsBlock(cells: readonly Cell[]): string {
  const head =
    "| Engine | Workload | Warm p50/p95 ms | Cold p50/p95 ms | Init p50/p95 ms | Tput /s | Peak RSS KiB | PDF KiB | PNG sim |";
  const sep = "|---|---|---|---|---|---|---|---|---|";
  return [
    "## Metrics (every cell maps to a workload id)",
    "",
    head,
    sep,
    ...cells.map(cellRow),
    "",
  ].join("\n");
}

/** Full RESULTS.md content for a results document. */
export function renderMarkdown(doc: ResultsDoc): string {
  return [
    "# Competitive benchmark results",
    "",
    "> Generated by the Phase 14 harness. Do not hand-edit — rerun `pnpm bench`.",
    "> Numbers are 'on this machine', never absolutes (spec AC-10.11).",
    "",
    contextBlock(doc.context),
    enginesBlock(doc.engines),
    metricsBlock(doc.cells),
  ].join("\n");
}
